{{- if and .Values.mongodb.enabled (not .Values.mongodb.externalUri) }}
{{- $templateVersion := default "kb8" .Values.kubeblocks.templateVersion }}
{{- if eq $templateVersion "kb9" }}
{{ include "sealaf.mongodb.kb9" . }}
{{- else if eq $templateVersion "kb8" }}
{{ include "sealaf.mongodb.kb8" . }}
{{- else }}
{{ fail (printf "unsupported kubeblocks.templateVersion: %s" $templateVersion) }}
{{- end }}
{{- end }}
