{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
{{- $serverJwtSecret := .Values.serverJwtSecret -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "sealaf.configSecretName" .) -}}
{{- if and (not $serverJwtSecret) $existingSecret (hasKey $existingSecret.data "SERVER_JWT_SECRET") -}}
{{- $serverJwtSecret = (index $existingSecret.data "SERVER_JWT_SECRET" | b64dec) -}}
{{- end -}}
{{- if not $serverJwtSecret -}}
{{- $serverJwtSecret = randAlphaNum 64 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sealaf.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "sealaf.name" . }}
    {{- include "sealaf.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVER_JWT_SECRET: {{ $serverJwtSecret | quote }}
  APP_MONITOR_URL: {{ .Values.appMonitorUrl | quote }}
  DATABASE_MONITOR_URL: {{ .Values.databaseMonitorUrl | quote }}
  {{- if .Values.mongodb.externalUri }}
  DATABASE_URL: {{ .Values.mongodb.externalUri | quote }}
  {{- end }}
{{- end }}
