apiVersion: v1
kind: Service
metadata:
  name: {{ include "sealaf.webName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sealaf.webSelectorLabels" . | nindent 4 }}
    {{- include "sealaf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      protocol: TCP
      targetPort: {{ .Values.web.service.targetPort }}
  selector:
    {{- include "sealaf.webSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sealaf.serverName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sealaf.serverSelectorLabels" . | nindent 4 }}
    {{- include "sealaf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      protocol: TCP
      targetPort: {{ .Values.server.service.targetPort }}
  selector:
    {{- include "sealaf.serverSelectorLabels" . | nindent 4 }}
